// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ksxusnodnvjvyfhnemrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzeHVzbm9kbnZqdnlmaG5lbXJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2ODYwNzksImV4cCI6MjA2MTI2MjA3OX0.X8OMdlx2ka2KeCjCtVejm3kUsZGUx750bpF5JN3O6oM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    headers: {
      'x-client-info': 'tamaya-ai-web-app'
    }
  }
});